global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: relatio-gateway
    static_configs:
      - targets:
          - relatio-gateway:8080
    metrics_path: /metrics
